# Site settings
title: 慕广陵的藏山阁
SEOTitle: 慕广陵的藏山阁
header-img: img/post-bg-desk.jpg
email: freerunner#foxmail.com
description: "Every failure is leading towards success."
keyword: "wangyubo Blog, 慕广陵的博客, wangyubo, 钰博， 修身养性， 文化产业, 文产, 古琴"
url: "http://muguangling.com"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/WangYuBo/wangyubo.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/mgl.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


        
# SNS settings
RSS: true
# weibo_username:     wangyubo
zhihu_username:     wangbyubo
github_username:    wangyubo
douban_ussername:   Free_Runner
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 895f6f62380e2dc262d8                            #生成的clientID
  clientSecret: a41665f5af72e9a2f28724a88bfceb2597e0949f    #生成的clientSecret
  repo: wangyubo.github.io    #仓库名称
  owner: wangyubo    #github用户名
  admin: wangyubo
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: muguangling.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


---
# layout:     keynote
# iframe:     "http://muguangling.com/2019/02/10/stones-in-the-bottle/"
---

# Friends
friends: [
    {
        title: "胡裕宁",
        href: "www.huyuning.com"
    }
]

theme: jekyll-theme-minimal
